Unify services names #29
CommerceWeavers/SyliusTpayPlugin pull request #76
Opened 2024-10-10 06:59 UTC by arti0090

Rename services, variables etc. named 'commerce_weavers.tpay' or 'commerce_weavers_tpay' to 'commerce_weavers_sylius_tpay'

2024-10-10 13:39 UTC, coldic3 requested changes

2024-10-10 13:39 UTC, coldic3 commented on config/services/tpay.php
> +        ->alias(TpayApiBankListProviderInterface::class, 'commerce_weavers_sylius_tpay.resolver.tpay_transaction_channel_resolver')
It still seems wrong, e.g. `commerce_weavers_sylius_tpay.tpay.resolver.tpay_transaction_channel_resolver` != `commerce_weavers_sylius_tpay.resolver.tpay_transaction_channel_resolver`.

2024-10-11 09:51 UTC, coldic3 approved these changes

2024-10-11 11:09 UTC, jakubtobiasz approved these changes

2024-10-11 11:09 UTC, merged